services:
  org-runner:
    build: .
    image: github-runner-uv:latest
    restart: unless-stopped
    environment:
      ORG_NAME: "${ORG_NAME}"
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      RUNNER_SCOPE: "${RUNNER_SCOPE}"
      RUNNER_NAME: "${RUNNER_NAME}"
      LABELS: "${LABELS}"
      EPHEMERAL: "${EPHEMERAL}"
      DOCKER_HOST: "unix:///var/run/docker-host.sock"
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker-host.sock
      - org-runner-work:/tmp/runner/work

volumes:
  org-runner-work:
