services:
  repo-runner:
    build: .
    image: github-runner-uv:latest
    restart: unless-stopped
    environment:
      REPO_URL: "${REPO_URL}"
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      RUNNER_SCOPE: "${RUNNER_SCOPE}"
      RUNNER_NAME: "${RUNNER_NAME}"
      LABELS: "${LABELS}"
      EPHEMERAL: "${EPHEMERAL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo-runner-work:/tmp/runner/work

volumes:
  repo-runner-work:
